services:
  postgres:
    image: postgres:15
    container_name: e-com-db
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecommerce_user -d ecommerce_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: e-com-app
    ports:
      - "8080:8080"
    environment:
      # Override database URL for Docker network
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce_db
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data: